# only for evaluation
DATA:
  IMG_SIZE: 512
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window16_512
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 16
TEST:
  CROP: True