# only for evaluation
DATA:
  IMG_SIZE: 512
MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window16_512
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 16
TEST:
  CROP: False