# only for evaluation
DATA:
  IMG_SIZE: 512
MODEL:
  TYPE: swin
  NAME: swin_large_patch4_window16_512
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 16
TEST:
  CROP: True